export { default as FamiliaPlatos } from './FamiliaPlatos'
export { default as FamiliaVinos } from './FamiliaVinos'
export { default as FamiliaBar } from './FamiliaBar'
export { default as Loading } from './loading'
export { default as Destilados } from './Destilados'
export { default as Coffe } from './Coffe'
export { default as Licor } from './Licor'
export { default as Beer} from './Beer'
export { default as Bars } from './bars'
export { default as WinePromo } from './winePromo'